### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by AbhigyanKumar** [yahoofinancelive/yliveticker#3]
**Subject**
What's behind the scenes?

**Question**
I am really curious about is because the Yahoo! Finance WebSocket just sends back a horribly jumbled `base64` string.

**Comment by alparamonov** [comment]
The Yahoo Websocket returns a light-weight, strictly typed data, encoded with protobuf. This is why you get that weird string back. This package decodes the protobuf and gives you the result.

**Comment by AbhigyanKumar** [comment]
Yeah, you're right! I just figured it out after seeking into the internals of the package.

**Comment by markosole** [comment]
Would it be possible to use this method to decode and emit decoded data to another server? - Like using it as decode gateway or something. This is first time I am running py script and have no idea hw this works. And is there a way to listen for after hours trading?
Thx!

**Comment by alparamonov** [comment]
Sure, it can be done. Your python code can run locally or on server/in the cloud. Depending on what you want to achieve, you can run a service and inject the data further in the next service for real time analytics or you can redirect the stream to storage for batch analytics later.

**Comment by NawtJ0sh** [comment]
@alparamonov the protobuf encoding and decoding is here

https://gist.github.com/Technetium1/6fd5a0530772c298d5ea1fad38f03a58/#file-ezcapecancer-chat-js-L4438

could you try helping me create a .proto file for it? 

thanks
