### ISSUE TITLE
Seems 16

### ISSUE THREAD

**Issue by AbhigyanKumar** [yahoofinancelive/yliveticker#5]
**Subject**
Number of quotes data in demand seems to be fixed to 16.

**Question**
I tried playing around with the Yahoo! Finance WebSocket. It seems that the number of quotes data in demand should only be 16. Is it true?

**Comment by alparamonov** [comment]
Thanks for testing the package! I can't tell you for sure because there are no limitations for the number of symbols from the package's code. The limit you encountered is induced from Yahoo.
