### ISSUE TITLE
FUTURES not UPDATING

### ISSUE THREAD

**Issue by kandahar-dev** [yahoofinancelive/yliveticker#7]
**Describe the bug**
Don't know why but Futures do not update

**To Reproduce**
Ask for Gold Future, for example, GC=F
**Expected behavior**
Should get updates from GC=F price 

**Environment (please complete the following information):**
 - Python Version: 2.7.16
 - OS: raspbian
 - Version 4.19.97-v7+ #1294

**Additional context**
Works for tickers like AAPL. Fails for BZ=F, CL=F, ES=F, etc

**Comment by alparamonov** [comment]
I can confirm that I haven't received any messages within ~30 minutes for GC=F ticker. For some reason, the server doesn't return data for this ticker. I tested also without yliveticker, just directly the websocket endpoint, and got the same results. One guess is that we both tested in low-volume market phase, when there was no data.

If the server doesn't return live information for a ticker, we can't fix it on the library side.

Also, please switch to python 3.5+ as v2.7 no longer supported. In fact, python 2 was deprecated [last year](https://www.python.org/doc/sunset-python-2/#:~:text=We%20have%20decided%20that%20January,as%20soon%20as%20you%20can.).

I will close the issue as there's no todo for now. If you have any updates, feel free to reopen.
